### ISSUE TITLE
Incorporation with Burp Suite request files

### ISSUE THREAD

**Issue by Konstantinos-Papanagnou** [Kostasssss/LFITester#21]
**Is your feature request related to a problem? Please describe.**
Not Related to a problem.

**Describe the solution you'd like**
It would be a good idea to add an argument to open a burp suite request file and automatically read the headers that should be used on the attack (To capture logon sessions, cookies, headers required by the website for validity purposes, etc) as well as the endpoint, etc.

**Additional context**
See SQLMap's similar feature for inspiration.

**Comment by kostas-pa** [comment]
Implemented by Timothy90990
