### ISSUE TITLE
Crashes on expired ssl

### ISSUE THREAD

**Issue by gprime31** [Kostasssss/LFITester#5]
![2022-01-17_18-26](https://user-images.githubusercontent.com/44535257/149847294-74b830a7-f472-45d4-bd67-386c887ad6ff.png)

**Comment by gprime31** [comment]
and for -L 
it crashes after max retry error instead of going on to the next url in the list.

**Comment by gprime31** [comment]
![2022-01-17_18-31](https://user-images.githubusercontent.com/44535257/149847543-fca62625-d8ba-4e98-9fdf-a62f2579f512.png)

**Comment by Konstantinos-Papanagnou** [comment]
Seems like we have to ignore the ssl certificate. I don't think that we care about the certificate in the first place so the fix should be straight forward.

**Comment by Konstantinos-Papanagnou** [comment]
@gprime31 if you could supply the exact line of the crash it would be really helpful. I'm guessing it crashed on the health check of the URL.

**Comment by gprime31** [comment]
Hi,
First to supress the ssl warnings.
![2022-01-18_06-08](https://user-images.githubusercontent.com/44535257/149926684-38c9fce7-d5ee-4826-973f-4717ca4312f1.png)

add:
import requests
requests.packages.urllib3.disable_warnings()
![2022-01-18_06-07](https://user-images.githubusercontent.com/44535257/149926778-b906c77d-e02a-45f7-bc99-16cfdf3fc64d.png)

to LFITester.py

**Comment by gprime31** [comment]
and for the ssl/timeout debug:
![2022-01-18_06-16](https://user-images.githubusercontent.com/44535257/149927643-9696f42f-67ec-4527-a51d-5d60973bf203.png)
![2022-01-18_06-17](https://user-images.githubusercontent.com/44535257/149927728-f201e991-06d0-4b2c-8e38-46403474b8d3.png)

**Comment by gprime31** [comment]
test on python 3.8 and 3.10 same errors for both.

**Comment by gprime31** [comment]
command used:
./LFITester.py -L lfi.txt

**Comment by gprime31** [comment]
it's strange, every run gives a different error:

try:
https://accounts.epicgames.com/authorize/index?client_id=5d6f8ef478c6490dbca8d80b27296897&response_type=code&state=e30%3D

./LFITester.py -u 'https://accounts.epicgames.com/authorize/index?client_id=5d6f8ef478c6490dbca8d80b27296897&response_type=code&state=e30%3D'
![2022-01-18_06-24](https://user-images.githubusercontent.com/44535257/149928575-488ed647-6526-48cd-85ce-e0d2262409f5.png)

**Comment by gprime31** [comment]
also, does it test each param in the url? or just the first one?

**Comment by gprime31** [comment]
tried with quotes "url" same thing.
![2022-01-18_06-30](https://user-images.githubusercontent.com/44535257/149929552-65136afb-6d66-485d-92c4-a7e48e6d4571.png)

**Comment by Konstantinos-Papanagnou** [comment]
I released a patch to resolve all 3 issues.
Issue 1: Ignore SSL Certificates (Some requests.get methods lacked the verify=False attribute)
Issue 2: Suppress SSL Warnings from within the Payload Manager (__init__) (Thanks for the suggestion)
Issue 3: Check if the server leaks it's Server Header (Containing Apache or Nginx attributes). If it doesn't leak them, we can automatically test both of the most common used http servers (Apache, Nginx) per user request.

I think these patches should resolve any issues you are dealing with. Check it and please respond in order to close the Issue Successfully.

On a side note, the tool usage is as follows:
https://url/?param=
It will only test the last parameter and it has to be empty to test it successfully. It will append on this url the payloads one by one. 
In a future release, we'll create a new feature to automatically detect the supplied parameters and test them all at once against every payload, so it won't be necessary to modify anything from the official URL endpoint.

Best Regards,
Konstantinos Papanagnou

**Comment by gprime31** [comment]
![2022-01-18_08-42](https://user-images.githubusercontent.com/44535257/149948764-57a5baf7-328d-455f-9f8f-51bb16f6dd73.png)
![2022-01-18_08-42_1](https://user-images.githubusercontent.com/44535257/149948781-5f5884a8-85b0-4523-9c91-11b7f17cd8e0.png)

**Comment by gprime31** [comment]
same problem,
also can you make a --batch flag to answer:  hit every known server type prompt to Y automatically?
when running a list -L

**Comment by gprime31** [comment]
Think it dies when it hits a rate limited site or WAF.

**Comment by Konstantinos-Papanagnou** [comment]
It seems like you are getting blocked after a point, since the Remote is aborting your connections.
I will add an except check for this to exit out gracefully...

**Comment by Konstantinos-Papanagnou** [comment]
As far as the --batch flag is concerned, i can look into it.

**Comment by gprime31** [comment]
or just skip to the next line in the txt file, because there are different domains in the txt file

**Comment by gprime31** [comment]
and we don't want to abort the whole file just because one endpoint has rate limiting in place
they all might not have rate limiting.

**Comment by Konstantinos-Papanagnou** [comment]
Grab the update and let me know if it catches the exception.
We had some issues with uncatchable exceptions in the past

**Comment by gprime31** [comment]
![2022-01-18_08-55](https://user-images.githubusercontent.com/44535257/149950679-2f0fb693-aadc-441e-b5ee-5358bb8d8a45.png)

**Comment by Konstantinos-Papanagnou** [comment]
yeah... python magic, now it should be good to go

**Comment by gprime31** [comment]
fixed :)

**Comment by Konstantinos-Papanagnou** [comment]
I'll start working on the --batch flag later. Shall i close this issue, or is there another problem in place?

**Comment by gprime31** [comment]
so if it looks for param=  ( it appends the payload after param= )
should I run qsreplace with blank to make all the param= blank?

**Comment by Konstantinos-Papanagnou** [comment]
yes exactly

**Comment by Konstantinos-Papanagnou** [comment]
but it will only append. So the payload will look something like this
http://url/?param1=&param2=../../../

**Comment by Konstantinos-Papanagnou** [comment]
I'll make a future release when i free some time, to make a feature to automatically detect and append to every parameter the payload

**Comment by gprime31** [comment]
> 

yes, so far it's working. can close, i'll open a new one if there are any more problems.
Thanks, and great tool. :)

**Comment by Konstantinos-Papanagnou** [comment]
Great, if an error persists please do open a new one.
Thanks a lot for the feedback, have a great day :)
